services:
  dataBase:
    image: postgres:13
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_PORT=${DB_PORT}
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql
